import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>MultiSender App</title>
        <meta
          content='Generated by @rainbow-me/create-rainbowkit'
          name='description'
        />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <footer className='fixed bottom-0 left-0 right-0 p-4'>
        <div className='text-center'>
          Copyright © 2024{' '}
          <a
            href='https://www.tokamak.network/'
            target='_blank'
            rel='noopener noreferrer'
            className='text-blue-600 hover:text-blue-800'
          >
            Tokamak Network
          </a>{' '}
          All Rights Reserved.
        </div>
      </footer>
    </div>
  );
};

export default Home;
